ufs: exynos: Adapt to new UFS API changes
Expose ufshcd_any_tag_in_use() so the Exynos UFS driver can use it.

../drivers/scsi/ufs/ufs-exynos.c:2008:13: error: no member named 'lrb_in_use' in 'struct ufs_hba'
 2008 |         if ((!hba->lrb_in_use) && (hba->clk_gating.active_reqs != 1)) {
      |               ~~~  ^
1 error generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>