ksu.config: disable SUS_SU as well
It requires Kprobes on KSU so it won't compile.

../drivers/kernelsu/kernel/sucompat.c:392:33: error: use of undeclared identifier 'su_kps'
  392 |         for (int i = 0; i < ARRAY_SIZE(su_kps); i++) {
      |                                        ^
../drivers/kernelsu/kernel/sucompat.c:392:33: error: use of undeclared identifier 'su_kps'
../drivers/kernelsu/kernel/sucompat.c:392:33: error: use of undeclared identifier 'su_kps'
../drivers/kernelsu/kernel/sucompat.c:393:7: error: use of undeclared identifier 'su_kps'
  393 |                 if (su_kps[i]) {
      |                     ^
4 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>