video: exynos/panel: ea8082: fix build with HMD
Samsung added support for HMD on this panel, but never finished it.

That leads to a flurry of errors like:

In file included from ../drivers/video/fbdev/exynos/panel/ea8082/ea8082.c:17:
In file included from ../drivers/video/fbdev/exynos/panel/ea8082/ea8082_panel.h:3:
../drivers/video/fbdev/exynos/panel/ea8082/ea8082_r9_a2_s0_panel.h:296:64: error: use of undeclared identifier 'init_gamma_mode2_hmd_brt_table'; did you mean 'init_gamma_mode2_brt_table'?
  296 |         [HMD_GAMMA_MAPTBL] = DEFINE_2D_MAPTBL(r9_a2_s0_hmd_brt_table, init_gamma_mode2_hmd_brt_table, getidx_gamma_mode2_hmd_brt_table, copy_common_maptbl),
      |                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                       init_gamma_mode2_brt_table
../drivers/video/fbdev/exynos/panel/ea8082/../panel.h:702:11: note: expanded from macro 'DEFINE_2D_MAPTBL'
  702 |                 .init = f_init,                 \
      |                         ^
../drivers/video/fbdev/exynos/panel/ea8082/ea8082.h:496:12: note: 'init_gamma_mode2_brt_table' declared here
  496 | static int init_gamma_mode2_brt_table(struct maptbl *tbl);
      |            ^
In file included from ../drivers/video/fbdev/exynos/panel/ea8082/ea8082.c:17:
In file included from ../drivers/video/fbdev/exynos/panel/ea8082/ea8082_panel.h:3:
../drivers/video/fbdev/exynos/panel/ea8082/ea8082_r9_a2_s0_panel.h:296:96: error: use of undeclared identifier 'getidx_gamma_mode2_hmd_brt_table'; did you mean 'getidx_gamma_mode2_brt_table'?
  296 |         [HMD_GAMMA_MAPTBL] = DEFINE_2D_MAPTBL(r9_a2_s0_hmd_brt_table, init_gamma_mode2_hmd_brt_table, getidx_gamma_mode2_hmd_brt_table, copy_common_maptbl),
      |                                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                       getidx_gamma_mode2_brt_table
../drivers/video/fbdev/exynos/panel/ea8082/../panel.h:703:13: note: expanded from macro 'DEFINE_2D_MAPTBL'
  703 |                 .getidx = f_getidx,             \
      |                           ^
../drivers/video/fbdev/exynos/panel/ea8082/ea8082.h:497:12: note: 'getidx_gamma_mode2_brt_table' declared here
  497 | static int getidx_gamma_mode2_brt_table(struct maptbl *);
      |            ^

And many more.

I've done just enough to get it building, using the dummy cmdtbl as a
placeholder for the missing HMD cmd tables.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>