video: exynos/panel: s6e3had: Fix build with GM2
Another case of a half-baked feature.

Leave the array empty since the driver clearly doesn't fully support this
feature.

../drivers/video/fbdev/exynos/panel/s6e3had/s6e3had_unbound3_a3_s0_panel.h:2849:18: error: use of undeclared identifier 'RES_GM2_FLASH_VBIAS1'
 2849 |         &s6e3had_restbl[RES_GM2_FLASH_VBIAS1],
      |                         ^
../drivers/video/fbdev/exynos/panel/s6e3had/s6e3had_unbound3_a3_s0_panel.h:2850:18: error: use of undeclared identifier 'RES_GM2_FLASH_VBIAS2'
 2850 |         &s6e3had_restbl[RES_GM2_FLASH_VBIAS2],
      |                         ^
../drivers/video/fbdev/exynos/panel/s6e3had/s6e3had_unbound3_a3_s0_panel.h:2876:35: error: invalid application of 'sizeof' to an incomplete type 'void *[]'
 2876 |         [PANEL_GM2_FLASH_RES_INIT_SEQ] = SEQINFO_INIT("gm2-flash-resource-init-seq", unbound3_a3_s0_gm2_flash_res_init_cmdtbl),
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../drivers/video/fbdev/exynos/panel/s6e3had/../panel.h:884:10: note: expanded from macro 'SEQINFO_INIT'
  884 |         .size = ARRAY_SIZE((_cmdtbl_)),         \
      |                 ^~~~~~~~~~~~~~~~~~~~~~
../include/linux/kernel.h:47:32: note: expanded from macro 'ARRAY_SIZE'
   47 | #define ARRAY_SIZE(arr) (sizeof(arr) / sizeof((arr)[0]) + __must_be_array(arr))
      |                                ^~~~~
3 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>