input: wacom: Set a reasonable command length for snprintf
The default value comes from sec_input, which is 10, but that's too small.

../drivers/input/wacom/wacom_i2c_sec.c:1291:2: error: 'snprintf' will always be truncated; specified size is 10, but format string expands to at least 12 [-Werror,-Wformat-truncation]
 1291 |         snprintf(tmp_buf, CMD_RESULT_WORD_LEN, "drxx_spec: ");
      |         ^
../drivers/input/wacom/wacom_i2c_sec.c:1305:2: error: 'snprintf' will always be truncated; specified size is 10, but format string expands to at least 12 [-Werror,-Wformat-truncation]
 1305 |         snprintf(tmp_buf, CMD_RESULT_WORD_LEN, "drxy_spec: ");
      |         ^
../drivers/input/wacom/wacom_i2c_sec.c:1319:2: error: 'snprintf' will always be truncated; specified size is 10, but format string expands to at least 12 [-Werror,-Wformat-truncation]
 1319 |         snprintf(tmp_buf, CMD_RESULT_WORD_LEN, "dryx_spec: ");
      |         ^
../drivers/input/wacom/wacom_i2c_sec.c:1333:2: error: 'snprintf' will always be truncated; specified size is 10, but format string expands to at least 12 [-Werror,-Wformat-truncation]
 1333 |         snprintf(tmp_buf, CMD_RESULT_WORD_LEN, "dryy_spec: ");
      |         ^
4 errors generated.

Signed-off-by: Flopster101 <nahuelgomez329@gmail.com>